Partage des données de simulation via l'iframe
datagir/nosgestesclimat-site pull request #298
Opened 2021-06-29 09:47 UTC by laem

Remplace #253

2021-06-29 13:43 UTC, laem commented
- [ ] intégrer cette option dans l'iframe, en optin de la part de l'intégrateur de l'iframe

2021-06-29 15:31 UTC, laem commented
@Sacramentix normalement c'est bon ! 

Pour activer l'option, il faut mettre un paramètre dans l'iframe.
Tu peux tester avec cette URL de branche :) 
<script id="nosgestesclimat" src="https://deploy-preview-298--nosgestesclimat.netlify.app/iframe.js" data-partagedatafinsimulation></script>

2021-08-16 15:46 UTC, laem commented
@Sacramentix est-ce que ça te convient :) ?

2021-08-23 19:50 UTC, Sacramentix commented
@laem il y a avait quelque problème sur les boutons les callbacks était pas les bons. J'ai fais les correctifs sur mon fork sur la branche iframedata.

2021-08-23 19:55 UTC, Sacramentix requested changes

2021-08-23 19:55 UTC, Sacramentix commented on source/sites/publicodes/IframeDataShareModal.tsx
> +						<button onClick={onReject} className="ui__ plain button">
callback onReject sur le bouton accepter au lieu de onAccept

2021-08-23 19:55 UTC, Sacramentix commented on source/sites/publicodes/IframeDataShareModal.tsx
> +						<button onClick={onAccept} className="ui__ button ">
callback onAccept sur le bouton refuser au lieu de onReject

2021-08-23 19:59 UTC, Sacramentix commented
[Ma branche iframedata avec le patch](https://github.com/Sacramentix/ecolab-climat/commit/4a8b48bda88ffe967d23140bda8ea3aee5fb2059).

2021-09-23 14:12 UTC, laem commented
Super merci, j'ai fait un cherry-pick de 4a8b48bda88ffe967d23140bda8ea3aee5fb2059
Je mets en ligne.

2021-09-23 14:16 UTC, merged