Propositions nouveaux trackers
datagir/nosgestesclimat-site pull request #411
Opened 2021-12-06 18:12 UTC by Clemog

2021-12-07 15:42 UTC, laem requested changes

2021-12-09 09:17 UTC, Clemog commented on source/sites/publicodes/Fin.js
> +		onClick={() => tracker.push(['trackEvent', 'NGC', 'Clic bouton action'])}
Je pense que ça permettrait d'avoir une vision plus précise des personnes qui réalisent le parcours utilisateurs de A à Z (intro, simulation, résultats, action). On pourrait comparer aussi les accès -> X venues sur l'URL "actions" dont X% via "Agir" et X% via "Passer à l'action"

2021-12-22 12:49 UTC, Clemog commented on source/sites/publicodes/ActionStack.tsx
> +		tracker.push(['trackEvent', 'NGC', 'Nbre votes cartes action'])
J'ai repris l'event dans le bon composant normalement :)

2022-01-18 10:32 UTC, laem commented
@Clemog j'ai ajouté deux commits, je te laisse merger si ça te va :)

2022-01-18 13:29 UTC, merged