Contextualisation du mode sondage
datagir/nosgestesclimat-site pull request #512
Opened 2022-04-19 12:53 UTC by Clemog

Pour répondre à #500 :)

Travail en cours, je complèterai la liste suivante au fur et à mesure :

- [ ] Désactiver le mode de visualisation temps réel dans les sondages par mail
- [ ] #495

2022-04-21 13:04 UTC, laem commented on source/sites/publicodes/conference/NamingBlock.tsx
> +					⚠️ Votre nom de salle ne peut pas contenir les caractères suivants :{' '}
C'est un peu violent la regex affichée à l'utilisateur comme ça ^^ 
Que penses-tu d'afficher plutôt "Le nom de salle ne peut que contenir des lettres, des chifffres et des tirets" ? 
Avec l'emoji :bulb: peut-être, moins alarmant que :warning: ?

2022-04-21 13:05 UTC, laem commented on source/sites/publicodes/conference/NamingBlock.tsx
> +					⚠️ Votre nom de salle ne peut pas contenir les caractères suivants :{' '}
Et peut-être n'afficher le message que si l'on détecte que l'utilisateur a essayé d'utiliser un mauvais charactère ?

2022-04-21 13:09 UTC, Clemog commented on source/sites/publicodes/conference/NamingBlock.tsx
> +					⚠️ Votre nom de salle ne peut pas contenir les caractères suivants :{' '}
Effectivement, j'ai aussi pensé à ça mais j'ai zappé de le changer après ! 😅
Et pour l'affichage, normalement, le message disparait au moment ou on tape le premier caractère et réapparait si on essaie de taper un # par exemple

2022-04-21 13:12 UTC, laem commented on source/sites/publicodes/conference/Survey.tsx
> +					{!hasDataState ? (
:+1: Bien plus propre de faire ce test en amont du composant Results en effet :)

2022-04-21 14:34 UTC, laem requested changes

2022-04-21 14:34 UTC, laem commented on source/components/conversation/Question.tsx
> +				{choices.children && choices.children.length > 5 && (
Si tu veux @Clemog je peux prendre ce taf de réorganisation, la mauvaise orga actuelle c'est clairement ma faute :sweat_smile:

2022-04-21 16:09 UTC, Clemog commented on source/sites/publicodes/conference/contextes-sondage/universités 2022.yaml
> +  par défaut: étudiant
Je crois que je n'utilise pas les valeurs par défaut, je supprime :)

2022-04-21 16:15 UTC, Clemog commented
> Autre souci, celui là je n'arrive pas à le débugguer : quand je teste `http://localhost:8080/sondage/universités 2022`, j'ai cette erreur.
> 
> ![image](https://user-images.githubusercontent.com/1177762/164476014-64a27b42-2869-4c38-980b-66f163119654.png)
> 
> Je pige pas où est appelée cette variable, car normalement elle contient `sondage` en préfixe non ?

C'est dans Survey.tsx, la variable surveyRule ligne 34, mais en fait le nom de la règle doit etre le même que le nom du fichier, je note pour expliquer

2022-04-21 16:16 UTC, Clemog commented on source/components/conversation/Question.tsx
> +				{choices.children && choices.children.length > 5 && (
J'avoue que j'ai fait un patch pas très joli mais j'avais bien en tête que Question.tsx devrait être décomposé

2022-04-29 15:46 UTC, Clemog commented
@laem pour moi c'est bon ! J'aurais aimer deux choses :
- accepter l'ajout une réponse au sondage seulement si les réponses de contexte sont remplies
- permettre un accès plus facile aux réponses sans que les réponses de "l'organisateur" soient ajouter dans le sondage (par rapport au cas de GRENOBLE DATA)

Dispo pour en discuter lundi matin !

2022-05-02 08:59 UTC, laem approved these changes

2022-05-02 09:00 UTC, laem commented
> accepter l'ajout une réponse au sondage seulement si les réponses de contexte sont remplies

Le plus simple me semble être de le faire côté client, non ?

2022-05-02 09:16 UTC, Clemog commented
> > accepter l'ajout une réponse au sondage seulement si les réponses de contexte sont remplies
> 
> Le plus simple me semble être de le faire côté client, non ?

Oui je pense aussi, à voir à quel moment on teste, il me semble qu'on lance appelle ADD_ANSWER_SURVEY à plusieurs reprises 

> > permettre un accès plus facile aux réponses sans que les réponses de "l'organisateur" soient ajouter dans le sondage (par rapport au cas de GRENOBLE DATA)
> 
> Ce n'est pas ce qui arrive quand on clique sur "Voir les données" dans la popup que tu avais ajouté récemment ?

Si jamais la personne a déjà fait le test, quand on clique sur voir les résultats sur la pop up, la situation n'est pas vide donc la réponse est ajoutée quand la page "survey" est chargée je pense et je trouve embêtant de supprimer la simulation de la personne si elle veut juste parcourir différents sondages qu'elle a créé (mais c'est un peu parallèle au sujet contexte)

2022-05-02 16:39 UTC, laem approved these changes

2022-05-02 16:39 UTC, laem commented on source/sites/publicodes/pages/GuideGroupe.js
> +import { EngineContext } from '../../../components/utils/EngineContext'
Ici tu peux utiliser l'`alias` 'Components/utils'. 
La liste des alias est dans webpack.common.js (et peut évoluer !)

2022-05-02 16:39 UTC, laem commented on source/sites/publicodes/conference/Instructions.tsx
> +							fonctionnalité "contextualisation de sondage" grâce à notre{' '}
Ici j'aurais mis le lien sur "Découvrez la
							fonctionnalité "contextualisation de sondage". Ça fait moins de texte, et le lien "notre page guide" est pas nécessaire.

2022-05-03 12:59 UTC, merged