Ré-introduction du bouton "Je ne sais pas" dans les mosaïques
datagir/nosgestesclimat-site pull request #604
Opened 2022-08-22 12:36 UTC by Clemog

**Pb actuel :** Aujourd'hui, au niveau d'une mosaïque, le bouton suivant apparait directement. Pour les mosaïques "select" Les valeurs par défaut sont bien pré-sélectionnées mais au clic sur suivant, elles sont mises à 0 si defaulttofalse est activé -> ce qui est attendu car rien n'est coché ! Seul échappe permet d'ajouter les valeurs par défaut à la situation mais on pourrait aussi supposé qu'une personne souhaite répondre rapidement ou clique sur suivant trop vite.

**Solution :** Je propose ici d'ajouter le bouton "je ne sais pas" qui permet de valider les valeurs par défaut (certes non explicite pour l'utilisateur) qui disparait si l'une des cases est coché. Le bouton suivant ne valide toujours "rien" s'il est cliqué en premier. Si une réponse est cochée, toutes les valeurs par défaut deviennent false

2022-08-23 08:55 UTC, Clemog commented
A mon avis, on peut essayer d'introduire les suggestions pour faciliter la saisie et trouver une solution à ce pb :)

2022-08-23 15:55 UTC, laem commented
À mon avis, le comportement de ta PR, ajouter un bouton je ne sais pas, est une nette amélioration. 
Je t'ai fait une petite remarque dans le code .

2022-08-23 16:01 UTC, laem commented on source/components/conversation/Conversation.tsx
> +		if (isAnsweredMosaic && mosaicQuestion?.options?.defaultsToFalse) {
Je ne comprends pas trop l'intérêt de ce hook. Est-ce que c'est pas un doublon de celui qui est dans *submit* ? Faudrait en tout cas documenter la répétition je pense si elle est pertinente.

2022-08-23 16:01 UTC, laem requested changes
CF ma remarque

2022-08-24 14:42 UTC, Clemog commented on source/components/conversation/Conversation.tsx
> +		if (isAnsweredMosaic && mosaicQuestion?.options?.defaultsToFalse) {
C'est assez discret mais important je pense. Ça concerne la différence à la valeur actuelle affichée

Le hook du submit permet de mettre les valeurs cochées par défaut (coche non visible) à false au moment du submit.  Par exemple au départ, la bouilloire est cochée (mais coche non visible). Si je ne clique pas sur la bouilloire, elle sera mise à false au moment du submit. Si je clique sur la bouilloire, la coche va apparaitre mais il n'y aura pas de variation du l'empreinte 

Ce hook permet de mettre à false toutes les valeurs par défaut à partir du moment ou on coche qque chose, donc au départ, si je coche bouilloire, on va avoir une "grande" diminution de l'empreinte car seront décochés (de manière non visible) toutes les valeurs par défaut

En ça cette solution n'est vraiment pas parfaite ..

2022-08-25 10:23 UTC, laem commented on source/components/conversation/Conversation.tsx
> +		if (isAnsweredMosaic && mosaicQuestion?.options?.defaultsToFalse) {
Ah oui OK je pige, bien vu ! N'hésite pas à mettre en évidence la différence entre celui-ci et l'autre, en insistant sur le fait que c'est pendant que l'utilisateur manipule la question, quand l'autre le fait après, et que les deux sont donc nécessaires.

2022-08-25 16:00 UTC, Clemog commented on source/components/conversation/Conversation.tsx
> +		if (isAnsweredMosaic && mosaicQuestion?.options?.defaultsToFalse) {
J'ai proposé une explication dans le code :)

2022-08-25 16:12 UTC, merged