Amélioration pour lighthouse
datagir/nosgestesclimat-site pull request #629
Opened 2022-09-01 15:56 UTC by laem

On est toujours mauvais sur la perf, et ça se répercute dans la console google. 

:warning: énorme opportunité : enlever "  !···if (!rules) return null". 

Charger les composants même si les règles sont pas chargées. 

- [x] je teste un déplacement de RulesProvider
- [x] vérifier que ça ne charge les règles qu'une fois
- [x] rond d'avancment cassé
- [ ] vérifier que tous les composants qui en ont besoin sont Wrappés, dont Action (mais seulement ses routes qui en ont besoin), Personas, etc.
- [x] le tuto peut être chargé sans rules, sauf une slide
- [x] charger les règles discrètement une fois que la home est chargée, pour qu'il n'y ait pas de ralentissement au clic sur "Faire le test" ? 
- [x] éventuellement, charger en lazy la page nouveauté
- [x] je crois qu'on pourrait carrément charger tout ce qui est contenu dans RulesProvider en lazy pour laisser tranquille la home + pages à propos et accélerer enore le chargement. 

J'ai une version qui semble fonctionnelle, mais je ne comprends pas le ralentissement quand on revient sur l'accueil depuis le test puis re-test. Il y a un truc qui se passe calculatoire et qui devrait pas. Peut-être un reparsing ? 

En termes de complexité de l'app, il y a des compromis (faut mettre des RulesProvider dans le router,et ils ne doivent pas être concurrents), mais le gain est juste énorme pour Google :o 

Je viens de voir cette discussion de @mquandalle très pertinente ici https://github.com/betagouv/publicodes/discussions/256

![image](https://user-images.githubusercontent.com/1177762/188491538-2583d55a-8d73-4fe0-bdee-5d7e690c2b8a.png)

![image](https://user-images.githubusercontent.com/1177762/188492470-0a8940b3-4277-4cf4-8f88-71c0a6f3c3f1.png)

En ressenti aussi pour l'accueil.

## Ensuite

Je me demande s'il ne faut pas qu'on utilise le Suspense de React 18, ça semble très adapté mais faut revoir du coup le chargement des données. Voir également comment ça marche pour la mise en commun du chargement entre les composants.

2022-09-06 08:09 UTC, laem commented
@Clemog @EmileRolley vu le changement, je veux bien une review du principe de cette PR. Si ça vous semble une bonne idée, et sinon comment faire mieux :)

2022-09-06 09:48 UTC, EmileRolley requested changes

2022-09-06 09:48 UTC, EmileRolley commented on source/RulesProvider.js
> +import { usePersistingState } from './components/utils/persistState'
Pourquoi ajouter cet import alors qu'il n'est pas utilisé par la suite ?

2022-09-06 09:48 UTC, EmileRolley commented on source/sites/publicodes/App.tsx
> +						<RulesProvider>
Pourquoi a-t-on besoins du `RulesProvider` pour la doc ?

2022-09-06 09:48 UTC, EmileRolley commented on source/sites/publicodes/Navigation.tsx
> +import RulesProvider from '../../RulesProvider'
Pourquoi cet import ?

2022-09-06 09:50 UTC, EmileRolley commented
J'ai quelques questions sur le code, mais sinon dans l'idée ça me parait bien ! Pouvoir fluidifier la navigation en répartissant les chargements me semble être une bonne solution :ok_hand:

2022-09-06 10:23 UTC, Clemog commented on index.html
> -
A quoi servent ces lignent de code à la base ? 
Je vois les options css `outdated-browser` plus haut, pourquoi ça ne s'affiche pas pour #335 ?

2022-09-06 10:40 UTC, Clemog commented on source/RulesProvider.js
> +	// to share the understanding of the version of the rules stored
C'est à dire ?

2022-09-06 10:52 UTC, Clemog commented on source/components/emoji.js
> +			height: '1',
Pourquoi ajouter ces attributs ?

2022-09-06 11:21 UTC, Clemog commented
J'ai proposé d'intégrer le tuto en lazy et de ne pas l'afficher à chaque fois que l'utilisateur recommence 
Le chargement en Lazy permet d'éviter le chargement du composant pour un utilisateur qui revient sur le site et ayant déjà vu le tuto

2022-09-06 11:33 UTC, Clemog commented on source/RulesProvider.js
Je veux bien quelques explications supplémentaires sur les changements dans ce composant ? J'ai du mal à comprendre avec le code

2022-09-06 12:00 UTC, Clemog commented
Autre remarque important, il me semble qu'en local, les changements dans le modèle ne relancent pas le chargement des règles

2022-09-06 12:06 UTC, laem commented on source/sites/publicodes/Navigation.tsx
> +import RulesProvider from '../../RulesProvider'
Relique :)

2022-09-06 12:06 UTC, laem commented on source/RulesProvider.js
> +import { usePersistingState } from './components/utils/persistState'
Relique :)

2022-09-06 12:07 UTC, laem commented on source/sites/publicodes/App.tsx
> +						<RulesProvider>
La documentation a besoin des règles, non ?

2022-09-06 12:08 UTC, laem commented on index.html
> -
Les règles d'outdated sont vraiment spécifiques à de très vieux navigateurs. On les a pas mises à jour. C'est très bancal comme solution, car il faudrait les adapter régulièrement. Peut-être qu'on peut trouver un moyen d'automatiser la détection des nav obsolètes pour leur afficher à tous le message.

2022-09-06 12:09 UTC, laem commented on source/RulesProvider.js
> +	// to share the understanding of the version of the rules stored
Quand les règles sont chargées, il faut qu'on les recharge au changement de branche par exemple. Donc il faut tester la version des règles qu'on a chargées.

2022-09-06 12:10 UTC, laem commented on source/components/emoji.js
> +			height: '1',
>  Mise en place d'aspect ratio pour éviter le CLS 

https://web.dev/optimize-cls/

2022-09-06 12:10 UTC, laem commented on source/RulesProvider.js
Yep on peut en parler.

2022-09-06 12:12 UTC, laem commented
> Il y avait un oubli de rulesprovider pour le tuto :)
Je propose d'intégrer le tuto en lazy et de ne pas l'afficher à chaque fois que l'utilisateur recommence
Le chargement en Lazy permet d'éviter le chargement du composant pour un utilisateur qui revient sur le site et ayant déjà vu le tuto

J'ai également testé de charger avec rulesprovider uniquement les slides qui en avaient besoin mais ça détériore l'expérience (chargement au passage d'une slide à l'autre). Je me demande pourquoi RulesProvider crée cette latence alors que les règles sont déjà chargées dans le state ..

Oui comme je le dis dans l'intro de la PR, il y a une latence que je ne comprends pas, à investiguer.

2022-09-07 10:21 UTC, laem commented
MAJ : je vais réécrire tout ça. RulesProvider restera tout en haut de l'arbre, mais WithRules permettra de s'assurer que ses composants enfants attendent que l'engine soit chargé pour commencer à être rendus.

2022-09-12 12:37 UTC, laem commented
@EmileRolley je me permets de merger, mais n'hésite pas à retester la navigation, on corrigera les problèmes éventuels.

2022-09-12 12:45 UTC, merged