Position bouton profil sur la Landing
datagir/nosgestesclimat-site pull request #672
Opened 2022-09-28 13:20 UTC by Clemog

Une proposition pour améliorer la visibilité du bouton pour "retrouver" sa simulation dès la landing

2022-10-04 16:46 UTC, laem commented
Je ne suis pas trop sûr du texte : en cliquant dessus je m'attendrais à aller sur le test, plutôt que le profil. 
L'idée de ce bouton profil était de ressembler aux profils d'un site connecté. 

Peut-être garder ce bouton profil plus discret, mais ajouter à ton emplacement un lien plus simple (genre "dashed-button") qui dirige également vers "faire le test" mais qui rassurerait l'utilisateur, avec un emoji sablier par exemple ?

2022-10-04 16:47 UTC, laem requested changes
CF mon commentaire

2022-10-05 07:16 UTC, Clemog commented
> Peut-être garder ce bouton profil plus discret, mais ajouter à ton emplacement un lien plus simple (genre "dashed-button") qui dirige également vers "faire le test" mais qui rassurerait l'utilisateur, avec un emoji sablier par exemple ?

Pour rassurer l'utilisateur dans quel sens ?

Sinon, on pourrait afficher un texte/redirection différent si la situation est complète ou pas ? 

Pour moi, ce bouton répond vraiment au cas d'usage : "Je reviens 6 mois après un premier test, je retrouve facilement ma simulation --> je suis rassuré mon test est bien sauvegardé !" 
A l'inverse, je ne me vois pas cliqué sur ce bouton profil autrement, quel cas d'usage avais-tu en tête ?

On pourrait aussi itérer avec une idée intéressante sur [l'historique du localstorage](https://github.com/datagir/nosgestesclimat-site/issues/400#issuecomment-1254786266) si je comprend bien

2022-10-05 14:03 UTC, laem approved these changes

2022-10-05 14:03 UTC, merged

2022-10-05 14:04 UTC, laem commented
On est finalement partis sur un bouton sur l'accueil plus discret, et un gros bouton "Finir mon test" sur la page profil, ainsi qu'afficher l'avancement.