🐛 Fix bugs resultats group
datagir/nosgestesclimat-site pull request #942
Opened 2023-04-06 10:52 UTC by Clemog

- [ ] affichage dans les stats de la page groupe des tests terminés seulement
- [ ] la moyenne affichées dans la bannière "groupe" correspond à la moyenne des tests complétés
- [ ] la moyenne dans la barre de session était toujours affichée "résultats en attente" (on moyennait sur une liste vide)
- [ ] on peut être dans plusieurs mode groupe en même temps -> voulu ?

2023-04-06 12:11 UTC, bjlaa commented on source/sites/publicodes/conference/GroupModeSessionVignette.tsx
> +					{completedTestsNumber != null && (
```suggestion
					{completedTestsNumber ?? (
```

2023-04-06 12:13 UTC, bjlaa commented on source/sites/publicodes/conference/SurveyBar.tsx
> +	const simulationArray = completedTests && Object.values(completedTests),
Si on fait ça à deux endroits, y'a pas moyen d'extraire la logique dans une fonction dédiée ?

2023-04-06 12:16 UTC, bjlaa commented
J'ai l'impression que c'est plutôt une bonne fonctionnalité de ne pas avoir à remplir ton questionnaire à chaque fois que tu rejoins un sondage/une conférence, ce que permet le fait de rejoindre plusieurs simulations si j'ai bien compris ?

2023-04-06 12:40 UTC, Clemog commented
> J'ai l'impression que c'est plutôt une bonne fonctionnalité de ne pas avoir à remplir ton questionnaire à chaque fois que tu rejoins un sondage/une conférence, ce que permet le fait de rejoindre plusieurs simulations si j'ai bien compris ?

Carrément ! Mais actuellement, tu tu participes à plusieurs sondages/conférences, les bandeaux s'accumulent et il faut les quitter un par un pour en sortir

2023-04-06 12:47 UTC, Clemog commented on source/sites/publicodes/conference/SurveyBar.tsx
> +	const simulationArray = completedTests && Object.values(completedTests),
Effectivement, logique qui se retrouve dans plusieurs endroits

2023-04-06 12:47 UTC, bjlaa commented
> Carrément ! Mais actuellement, tu tu participes à plusieurs sondages/conférences, les bandeaux s'accumulent et il faut les quitter un par un pour en sortir
Oulà pas tip top ouais 😕

2023-04-06 12:48 UTC, bjlaa commented on source/sites/publicodes/conference/SurveyBar.tsx
> +	const simulationArray = completedTests && Object.values(completedTests),
Peut-être pas le moment de faire ça tout de suite si c'est un fix urgent mais on peut peut-être se noter ça pour plus tard ?

2023-04-06 13:02 UTC, bjlaa approved these changes

2023-04-06 13:43 UTC, Clemog commented on source/sites/publicodes/conference/SurveyBar.tsx
> +	const simulationArray = completedTests && Object.values(completedTests),
J'ai essayé de refactoré un peu mais pas évident
C'est lié au fait qu'on a 2 modes, il y a des petites subtilités

2023-04-06 13:45 UTC, Clemog commented
Je pense qu'on est pas mal, j'espère que j'ai pas introduit de bugs

2023-04-06 13:54 UTC, Clemog commented
j'ai fait une issue pour le sujet:
- https://github.com/datagir/nosgestesclimat-site/issues/944

2023-04-06 13:57 UTC, bjlaa commented
> Je pense qu'on est pas mal, j'espère que j'ai pas introduit de bugs

Je peux tester si tu veux, y'a une manip particulière à faire ?

2023-04-06 14:04 UTC, bjlaa commented on source/sites/publicodes/conference/SurveyBar.tsx
> +	const simulationArray = completedTests && Object.values(completedTests),
Okay je vois, pareil c'était une suggestion mais c'est clairement moins urgent que le fix

2023-04-12 15:49 UTC, laem requested changes

2023-04-14 10:57 UTC, bjlaa commented on source/components/localisation/useOrderedSupportedRegions.ts
> +		supportedRegions &&
Intéressant, tu as quoi en tête comme alternative ? `throw` une erreur ?

2023-04-19 09:31 UTC, laem commented
Une chose bloquante de mon côté. 

C'était volontaire d'afficher dans la page de visualisation des résultats les tests non complétés. 

Car sans ça, la page n'est pas en direct. Elle ne bouge pas quand on répond aux questions, ça peut même donner l'impression que c'est cassé. Ça répond à l'usage du sondage en mode conférence en direct. 

Cela dit je vois bien le problème du fait d'inclure dans les résultats finaux du sondage des tests non complétés. Mais d'un autre côté, c'est aussi intéressant de se rendre compte que si 20% des gens n'ont pas fini le test, ces gens existent pour autant, ce sont peut-être les gens les moins sensibilités, donc leur attribuer une valeur moyenne est peut-être la moins pire chose à faire. 

Ça dépend de l'usage finalement, et donc à mon avis il faut mettre une case à cocher. 

Ça peut une case à cocher, d'un côté ou de l'autre :  
- [ ] mode temps réel : afficher les simulations pas encore terminées

Ou par la négative : 
- [ ] n'afficher que les tests complétés

2023-04-20 16:36 UTC, laem commented
> Question un peu annexe, c'est normal que le bandeau de conférence/sondage n'apparaisse pas sur l'écran agir ?

C'est volontaire en effet, étant donné qu'aucunes des actions de cet écran n'a d'impact sur le mode groupe.

2023-04-24 14:32 UTC, Clemog commented on source/components/localisation/useOrderedSupportedRegions.ts
> +		supportedRegions &&
Plus d'actualité, j'ai enlevé la condition qui semblait inutile

2023-04-24 17:48 UTC, bjlaa commented on source/sites/publicodes/conference/FilterBar.tsx
> +						onChange={() => setRealTimeMode(!realTimeMode)}
Je mettrais bien un tracker ici pour voir si l'option est utilisée
```suggestion
						onChange={() => {
						  tracker.push(['trackEvent', 'Mode groupe', realTimeMode ? 'Désactivation du mode temps réel' : 'Activation du mode temps réel' ])
						  setRealTimeMode(!realTimeMode)
						}}
```

2023-04-25 10:14 UTC, laem commented
> Mais du coup une fois sur l'écran action, on ne peut plus accéder au sondage

Si, les 3 autres options du menu affichent la bannière. Dont le bouton "Groupe" qui a été introduit pour donner plus de visibilité au mode groupe.

2023-04-25 10:44 UTC, laem commented
En termes de fonctionnalité, ça semble bon :+1: 

Mais je trouve que le choix est trop en retrait. À mon avis il devrait être très visible. 

Si je me rappelle bien, le but de ma PR de février https://github.com/datagir/nosgestesclimat-site/pull/829 c'était justement d'afficher tous les résultats des participants du sondage, en direct, donc y compris les tests non complétés. Notamment parce beaucoup de gens utilisent le sondage en mode conférence et avaient l'impression, vu que rien ne bougeait, que ça fonctionnait pas, pensaient directement à des problèmes de connexion. Je me suis fait avoir plein de fois également lors de tests. L'affichage séparé "participant vs complété" dans la barre est une nouveauté qui doit aider, mais je suis certain que beaucoup ne verront pas la subtilité. 

Ici on revient un peu en arrière en tranchant en faveur des utilisateur qui utilisent le sondage en mode asynchrone avec résultats finaux.

Que penses-tu de mettre le choix hors du bouton filtre, qui est très peu visible, le mettre tout en haut ? 

Autre point, la PR introduit le même comportement pour la conférence on dirait ? Du coup, on perd toute l’interactivité du mode groupe dans les deux modes. Ça me semble pourtant être une des grosses raisons de son succès...

Globalement, ces deux modes sont si proches en termes d'UI et d'UX, que la confusion me semble trop grande. Si on décide de faire du sondage un mode par défaut non interactif, peut-être qu'il vaut mieux alors bien acter cette séparation, en amont ou en aval. 

En aval, je reviens sur l'idée d'un bouton radio massif tout en haut, un peu comme le radio de la page /groupe, pour laisser l'utilisateur choisir entre deux modes de visualisation des résultats : par exemple "instantané" vs "bilan". 

![image](https://user-images.githubusercontent.com/1177762/234253299-06d79510-335d-4698-87ea-52712c8d935b.png)


Pour l'amont, il faudrait introduire une distinction entre conférence et sondage asynchrone. J'en fais une issue, ça dépasse clairement cette PR. https://github.com/datagir/nosgestesclimat-site/issues/1000

2023-04-25 10:52 UTC, laem commented
Autre idée : ne pas choisir entre les deux modes de visualisation, et les mêler. Je m'explique. 

Un utilisateur qui n'aurait pas atteint par exemple 90% de sa simulation, apparaîtrait de façon autre sur le graphique. 

Un utilisateur qui aurait terminé sa simulation serait confirmé visuellement. On pourrait même confirmer les catégories indépendamment des autres : A aurait fini transport, donc sa boule serait pleine, mais pas encore terminé alimentation. 

Sur le résultat moyen final, on verrait seulement le score des terminés. Dans les options de filtre, on pourrait afficher le score moyen simulations pas finies comprises. 

Ça me semble être le meilleur des deux mondes : l'UI montre l'intéractivité, on peut se voir bouger. Le résultat chiffré montre le bilan définitif provisoire. Il est renommé en "Moyenne du groupe : 7,6 tonnes" -> "Moyenne des tests terminés : 6,4 tonnes"

2023-04-25 10:57 UTC, bjlaa commented
> Un utilisateur qui n'aurait pas atteint par exemple 90% de sa simulation, apparaîtrait de façon discrète mais visible sur le graphique.

Je suis pour cette dernière option !

Je pense aussi que la dichotomie sondage/conférence fait peut-être sens et est utile pour nous en tant que devs mais à moins d'utilité et est prête sans doute plus à confusion qu'autre chose pour l'utilisateur, qui lui devrait, à mon sens, simplement voir dans les options du mode groupe un select input avec deux options "Persister les données", "Ne pas persister les données" (labels à affiner)

2023-04-25 15:02 UTC, Clemog commented
Nouvelle version : 
<img width="896" alt="image" src="https://user-images.githubusercontent.com/55186402/234319347-3214ea82-8905-40dd-8d42-ed40e3ce05ab.png">

2023-04-25 15:03 UTC, Clemog commented
Dernière review j'espère @laem et @bjlaa, j'ai des doutes sur le cas de FilterBar et les `position: relative`.. 

Pour cette version, la solution me semble acceptable et on pourra itérer sur les dernières discussions par la suite

2023-04-25 15:38 UTC, laem commented
Cool ! Ça me semble une bonne itération en attendant la suite. 

Par contre, mode conf, hors de la page /conférence, j'ai l'impression que la barre n'affche plus le résultat. Sur le mode sondage, ça fonctionne. 

![image](https://user-images.githubusercontent.com/1177762/234329599-89c340b2-c35a-46dd-a7e9-b59c6bcc36b2.png)

2023-04-26 07:02 UTC, Clemog commented
> Par contre, mode conf, hors de la page /conférence, j'ai l'impression que la barre n'affche plus le résultat. Sur le mode sondage, ça fonctionne. En prod ça fonctionne actuellement.

Je me demande si c'est pas le comportement normal, dans la barre en haut, j'affichais la moyenne pour les résultats terminés uniquement mais effectivement ce n'est pas cohérent avec le mode "temps réel" par défaut. C'est bien ça que tu mentionnes ?

2023-04-26 15:42 UTC, merged